name: Run checks in dev

on:
  pull_request:
    branches:
      - dev

jobs:
  ci:
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    uses: AllenNeuralDynamics/.github/.github/workflows/test-ci.yml@main
    with:
      python-version: ${{ matrix.python-version }}
